import Takbir from "../assets/prayer/Takbir.webp";
import Ithidhaal from "../assets/prayer/Ithidhaal.webp";
import Rukoo from "../assets/prayer/Rukoo.webp";
import Samiallah from "../assets/prayer/Takbir.webp";
import Sujoodh from "../assets/prayer/Sujoodh.webp";
import betweenSajdha from "../assets/prayer/betweenSajdha.webp";
import Sujoodh2 from "../assets/prayer/Sujoodh.webp";
import Ithidhaal2 from "../assets/prayer/Ithidhaal.webp";
import Rukoo2 from "../assets/prayer/Rukoo.webp";
import Takbir3 from "../assets/prayer/Takbir.webp";
import Sujoodh3 from "../assets/prayer/Sujoodh.webp";
import betweenSajdha2 from "../assets/prayer/betweenSajdha.webp";
import Sujoodh4 from "../assets/prayer/Sujoodh.webp";
import Tashahhudh from "../assets/prayer/Tashahhud.webp";
import Salaam from "../assets/prayer/Salaam.webp";

export const fajrImageMap = {
  "Takbir.webp": Takbir,
  "Ithidhaal.webp": Ithidhaal,
  "Rukoo.webp": Rukoo,
  "Takbir2.webp": Samiallah,
  "Sujoodh.webp": Sujoodh,
  "betweenSajdha.webp": betweenSajdha,
  "Sujoodh2.webp": Sujoodh2,
  "Ithidhaal2.webp": Ithidhaal2,
  "Rukoo2.webp": Rukoo2,
  "Takbir3.webp": Takbir3,
  "Sujoodh3.webp": Sujoodh3,
  "betweenSajdha2.webp": betweenSajdha2,
  "Sujoodh4.webp": Sujoodh4,
  "Tashahhud.webp": Tashahhudh,
  "Salaam.webp": Salaam,
};

export const dhuhaImageMap = {
  "Takbir.webp": Takbir,
  "Ithidhaal.webp": Ithidhaal,
  "Rukoo.webp": Rukoo,
  "Takbir2.webp": Samiallah,
  "Sujoodh.webp": Sujoodh,
  "betweenSajdha.webp": betweenSajdha,
  "Sujoodh2.webp": Sujoodh2,
  "Ithidhaal2.webp": Ithidhaal2,
  "Rukoo2.webp": Rukoo2,
  "Takbir3.webp": Takbir3,
  "Sujoodh3.webp": Sujoodh3,
  "betweenSajdha2.webp": betweenSajdha2,
  "Sujoodh4.webp": Sujoodh4,
  "Tashahhud.webp": Tashahhudh,
  "Salaam.webp": Salaam,
};
export const dhuhrImageMap = {
  "Takbir.webp": Takbir,
  "Ithidhaal.webp": Ithidhaal,
  "Rukoo.webp": Rukoo,
  "Takbir2.webp": Samiallah,
  "Sujoodh.webp": Sujoodh,
  "betweenSajdha.webp": betweenSajdha,
  "Sujoodh2.webp": Sujoodh2,
  "Takbir3.webp": Takbir,
  "Ithidhaal2.webp": Ithidhaal2,
  "Rukoo2.webp": Rukoo2,
  "Takbir4.webp": Takbir3,
  "Sujoodh3.webp": Sujoodh3,
  "betweenSajdha2.webp": betweenSajdha2,
  "Sujoodh4.webp": Sujoodh4,
  "Tashahhud.webp": Tashahhudh,
  "Takbir5.webp": Takbir,
  "Ithidhaal3.webp": Ithidhaal2,
  "Rukoo3.webp": Rukoo2,
  "Takbir6.webp": Takbir3,
  "Sujoodh5.webp": Sujoodh3,
  "betweenSajdha3.webp": betweenSajdha2,
  "Sujoodh6.webp": Sujoodh4,
  "Takbir7.webp": Takbir,
  "Ithidhaal7.webp": Ithidhaal,
  "Rukoo8.webp": Rukoo,
  "Takbir8.webp": Samiallah,
  "Sujoodh8.webp": Sujoodh,
  "betweenSajdha8.webp": betweenSajdha,
  "Sujoodh9.webp": Sujoodh2,
  "Tashahhud2.webp": Tashahhudh,
  "Salaam.webp": Salaam,
};
export const asrImageMap = {
  "Takbir.webp": Takbir,
  "Ithidhaal.webp": Ithidhaal,
  "Rukoo.webp": Rukoo,
  "Takbir2.webp": Samiallah,
  "Sujoodh.webp": Sujoodh,
  "betweenSajdha.webp": betweenSajdha,
  "Sujoodh2.webp": Sujoodh2,
  "Takbir3.webp": Takbir,
  "Ithidhaal2.webp": Ithidhaal2,
  "Rukoo2.webp": Rukoo2,
  "Takbir4.webp": Takbir3,
  "Sujoodh3.webp": Sujoodh3,
  "betweenSajdha2.webp": betweenSajdha2,
  "Sujoodh4.webp": Sujoodh4,
  "Tashahhud.webp": Tashahhudh,
  "Takbir5.webp": Takbir,
  "Ithidhaal3.webp": Ithidhaal2,
  "Rukoo3.webp": Rukoo2,
  "Takbir6.webp": Takbir3,
  "Sujoodh5.webp": Sujoodh3,
  "betweenSajdha3.webp": betweenSajdha2,
  "Sujoodh6.webp": Sujoodh4,
  "Takbir7.webp": Takbir,
  "Ithidhaal7.webp": Ithidhaal,
  "Rukoo8.webp": Rukoo,
  "Takbir8.webp": Samiallah,
  "Sujoodh8.webp": Sujoodh,
  "betweenSajdha8.webp": betweenSajdha,
  "Sujoodh9.webp": Sujoodh2,
  "Tashahhud2.webp": Tashahhudh,
  "Salaam.webp": Salaam,
};
export const maghribImageMap = {
  "Takbir.webp": Takbir,
  "Ithidhaal.webp": Ithidhaal,
  "Rukoo.webp": Rukoo,
  "Takbir2.webp": Samiallah,
  "Sujoodh.webp": Sujoodh,
  "betweenSajdha.webp": betweenSajdha,
  "Sujoodh2.webp": Sujoodh2,
  "Takbir3.webp": Takbir,
  "Ithidhaal2.webp": Ithidhaal2,
  "Rukoo2.webp": Rukoo2,
  "Takbir4.webp": Takbir3,
  "Sujoodh3.webp": Sujoodh3,
  "betweenSajdha2.webp": betweenSajdha2,
  "Sujoodh4.webp": Sujoodh4,
  "Tashahhud.webp": Tashahhudh,
  "Takbir5.webp": Takbir,
  "Ithidhaal3.webp": Ithidhaal2,
  "Rukoo3.webp": Rukoo2,
  "Takbir6.webp": Takbir3,
  "Sujoodh5.webp": Sujoodh3,
  "betweenSajdha3.webp": betweenSajdha2,
  "Sujoodh6.webp": Sujoodh4,
  "Tashahhud2.webp": Tashahhudh,
  "Salaam.webp": Salaam,
};

export const ishaImageMap = {
  "Takbir.webp": Takbir,
  "Ithidhaal.webp": Ithidhaal,
  "Rukoo.webp": Rukoo,
  "Takbir2.webp": Samiallah,
  "Sujoodh.webp": Sujoodh,
  "betweenSajdha.webp": betweenSajdha,
  "Sujoodh2.webp": Sujoodh2,
  "Takbir3.webp": Takbir,
  "Ithidhaal2.webp": Ithidhaal2,
  "Rukoo2.webp": Rukoo2,
  "Takbir4.webp": Takbir3,
  "Sujoodh3.webp": Sujoodh3,
  "betweenSajdha2.webp": betweenSajdha2,
  "Sujoodh4.webp": Sujoodh4,
  "Tashahhud.webp": Tashahhudh,
  "Takbir5.webp": Takbir,
  "Ithidhaal3.webp": Ithidhaal2,
  "Rukoo3.webp": Rukoo2,
  "Takbir6.webp": Takbir3,
  "Sujoodh5.webp": Sujoodh3,
  "betweenSajdha3.webp": betweenSajdha2,
  "Sujoodh6.webp": Sujoodh4,
  "Takbir7.webp": Takbir,
  "Ithidhaal7.webp": Ithidhaal,
  "Rukoo8.webp": Rukoo,
  "Takbir8.webp": Samiallah,
  "Sujoodh8.webp": Sujoodh,
  "betweenSajdha8.webp": betweenSajdha,
  "Sujoodh9.webp": Sujoodh2,
  "Tashahhud2.webp": Tashahhudh,
  "Salaam.webp": Salaam,
};
